// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGZ4RtYH8Oy_5hXUTvalKv0sfwaGXBgs',
    appId: '1:646374909031:web:d47f12528fbc3c623720c2',
    messagingSenderId: '646374909031',
    projectId: 'comp5b-24-51fe6',
    authDomain: 'comp5b-24-51fe6.firebaseapp.com',
    storageBucket: 'comp5b-24-51fe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQynyFbL_6vfvgA2mRBLniSWYq76lxrc',
    appId: '1:646374909031:android:daebd4baaa04182a3720c2',
    messagingSenderId: '646374909031',
    projectId: 'comp5b-24-51fe6',
    storageBucket: 'comp5b-24-51fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuZdBJlmIneyMNLp9BJhX2JF66QK5Wdg',
    appId: '1:646374909031:ios:2415f0a1cbdeb67f3720c2',
    messagingSenderId: '646374909031',
    projectId: 'comp5b-24-51fe6',
    storageBucket: 'comp5b-24-51fe6.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
